export const SITE_NAME = 'exile.party';
export const SITE_TAGLINE = 'Third-party tools for Path of Exile 1 and 2.';
export const REPO_URL = 'https://github.com/poetoollist/exile.party';
export const CATALOG_PATH = 'tools/<tool-id>/about.yaml';
/** GitHub opens a new per-tool metadata file and forks the repo when needed. */
export const NEW_TOOL_URL = `${REPO_URL}/new/main/tools?filename=your-tool%2Fabout.yaml`;
export const ISSUE_URL = `${REPO_URL}/issues/new`;

/** Absolute origin, needed because Open Graph tags reject relative image URLs. */
export const SITE_URL = 'https://exile.party';
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

/** Card generated by `bun run og` into static/og. */
export function ogImage(file: string): string {
	return `${SITE_URL}/og/${file}`;
}
